# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Blooring' do
pod 'GoogleMobileVision/FaceDetector'
pod 'GoogleMobileVision/MVDataOutput'
end

target 'Blooring-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Blooring-tvOS

  target 'Blooring-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
